## Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing", arr[5:9])
print("With Step",arr[2:6:2])
print("Negativing Indexing",arr[-3])

Basic Slicing [5 6 7 8]
With Step [2 4]
Negativing Indexing 8


In [4]:
arr_2d = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])
print("Specific element",arr_2d[1,2])
print("Entire Row: ",arr_2d[2])
print("Entire Row: ",arr_2d[:,1])

Specific element 7
Entire Row:  [ 9 10 11 12]
Entire Row:  [ 2  6 10]


## Sorting

In [5]:
unsorted = np.array([1,3,7,4,8,9,12,11,8])

print("Sorted Array: ",np.sort(unsorted))


arr_2d_unsorted = np.array([[1,3],[1,2],[2,3]])

print("Sorted 2D array by column",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D array by column",np.sort(arr_2d_unsorted,axis=1))


Sorted Array:  [ 1  3  4  7  8  8  9 11 12]
Sorted 2D array by column [[1 2]
 [1 3]
 [2 3]]
Sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


## Filter

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_numbers = numbers[numbers%2==0]
print("Even Numbers",even_numbers)


Even Numbers [ 2  4  6  8 10]


## Filter with Mask

In [7]:
mask = numbers > 5
print("Print Numbers greater than 5 ",numbers[mask])

Print Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [9]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers >5)
print(where_result)

print("NP where ",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [22]:
condition_array = np.where(numbers > 5,numbers*2,numbers) 
print(condition_array)

condition_array_2 = np.where(numbers <= 5,True,False)
print(condition_array_2)

[ 1  2  3  4  5 12 14 16 18 20]
[ True  True  True  True  True False False False False False]


### Adding and removing data 

In [28]:
arr1 = np.array ([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility 

In [32]:
a = np.array ([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])


print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [45]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))

print("With new Row",with_new_row)


new_col = np.array([[3],[4]])

with_new_col = np.hstack((original,new_col))

print("With new column",with_new_col)

With new Row [[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 3]
 [3 4 4]]
