In [4]:
import numpy as np

### Creating array from list

In [7]:
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])
print("Id array",arr_1d)
print("2D array",arr_2d)



Id array [1 2 3]
2D array [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [8]:
py_list = [1,2,3,4]
print("Python list multiplication: ",py_list*2)

np_array = np.array([1,2,3,4])

print("Numpy array multiplication: ",np_array *2)

Python list multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication:  [2 4 6 8]


### Creating array from strach

In [18]:
zeros = np.zeros((3,5))
print("Zeros Array: \n",zeros)

ones = np.ones((3,5))
print("Ones Array: \n",ones)

full = np.full((3,3),3)
print("Constants Arrary: \n",full)

Zeros Array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Constants Arrary: 
 [[3 3 3]
 [3 3 3]
 [3 3 3]]
