In [2]:
import numpy as np

### Creating array from list

In [3]:
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])
print("Id array",arr_1d)
print("2D array",arr_2d)



Id array [1 2 3]
2D array [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [4]:
py_list = [1,2,3,4]
print("Python list multiplication: ",py_list*2)

np_array = np.array([1,2,3,4])

print("Numpy array multiplication: ",np_array *2)

Python list multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication:  [2 4 6 8]


### Creating array from strach

In [5]:
zeros = np.zeros((3,5))
print("Zeros Array: \n",zeros)

ones = np.ones((3,5))
print("Ones Array: \n",ones)

full = np.full((3,3),3)
print("Constants Arrary: \n",full)

random = np.random.random((2,4))

print("Random array: \n",random)

Zeros Array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Constants Arrary: 
 [[3 3 3]
 [3 3 3]
 [3 3 3]]
Random array: 
 [[0.6254278  0.57262392 0.05056655 0.513103  ]
 [0.83230519 0.57929461 0.18877368 0.76125015]]


### Vector, Matrix and Tensor

In [6]:
vector = np.array([1,2,3])
print("Vector: ",vector)

matrix = np.array([1,2,3])
print("Matrix: ",matrix)

tensor = np.array([[[1,2],[5,4]],[[3,6],[9,5]]])

print("Tensor: \n",tensor)


Vector:  [1 2 3]
Matrix:  [1 2 3]
Tensor: 
 [[[1 2]
  [5 4]]

 [[3 6]
  [9 5]]]


### Array Properties

In [7]:
arr = np.array([[1,2,3],
               [4,5,6]])

print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("DType: ",arr.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


### Array Reshaping

In [10]:
arr = np.arange(12)

print("Original Array: ", arr)

reshaped = arr.reshape(3,4)

print("Reshaped Array: \n",reshaped)

flattened = reshaped.flatten()
print("Flattened Array: ",flattened)

# Revaled return views instead of copy
revaled = reshaped.ravel()
print("Revaled Array: ",revaled)

transpose = reshaped.T
print("Transpose: \n",transpose)


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Revaled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
